libs/pages/src/lib/home/home.component.html
libs/pages/src/lib/home/home.component.ts
libs/shared/src/lib/carousel/carousel.component.ts
libs/shared/src/lib/shared.module.ts

Made carousel work with asynchronous data from parent component

:poop: Carousel works with async calls

---

apps/client/src/app/app.component.html
apps/client/src/app/app.component.ts
apps/client/tailwind.config.js
libs/pages/src/lib/board-game-details/board-game-details.component.html
libs/pages/src/lib/board-game-details/board-game-details.component.scss
libs/pages/src/lib/board-game-details/board-game-details.component.ts
libs/pages/src/lib/home/home.component.html
libs/pages/src/lib/home/home.component.ts
libs/pages/src/lib/pages.module.ts
libs/shared/src/lib/carousel/carousel.component.ts

added code and css for the BoardGameDetails

:poop:Added BoardGameDetails

---

libs/pages/src/lib/board-game-details/board-game-details.component.ts
libs/pages/src/lib/board-game-search/board-game-search.component.html
libs/pages/src/lib/board-game-search/board-game-search.component.ts
libs/shared/src/lib/carousel/carousel.component.html
libs/shared/src/lib/carousel/carousel.component.ts
libs/shared/src/lib/classes/search-result.ts

BoardGameDetails updated as specified

:poop:BoardGameDetails accepts id as parameter

---

libs/pages/src/lib/board-game-details/board-game-details.component.ts
libs/pages/src/lib/home/home.component.ts
libs/shared/src/lib/carousel/carousel.component.html
libs/shared/src/lib/carousel/carousel.component.scss
libs/shared/src/lib/carousel/carousel.component.ts

fixed local storage of first element in collection

:bug: fixed local storage

---

apps/client/src/app/app.component.html
libs/pages/src/lib/board-game-details/board-game-details.component.html
libs/pages/src/lib/board-game-search/board-game-search.component.html
libs/pages/src/lib/home/home.component.html

Removed header from app.component.html and instead inserted it in all pages to fix testing.

:bug:(UI): Removed header from app.component.html and put it in all pages

---

libs/pages/src/lib/home/home.component.ts
libs/shared/src/lib/carousel/carousel.component.ts

Fixed bug where carousel was displaying empty collection when the last entry was removed.

:bug: Carousel

---

libs/pages/src/lib/board-game-details/board-game-details.component.scss
libs/shared/src/lib/carousel/carousel.component.html
libs/shared/src/lib/carousel/carousel.component.scss
libs/shared/src/lib/footer/footer.component.scss

Style fixes for carousel, board game details, footer.

💄(UI): Style fixes

---

libs/pages/src/lib/view-collection/view-collection.component.html
libs/pages/src/lib/view-collection/view-collection.component.ts

removal functionality added to the collection view page.

Added removal functionality

---

libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts

:bug:(UI): Game sessions fix

---

env
libs/client-lib/src/lib/shared/components/header/header.component.html
libs/client-lib/src/lib/shared/components/header/header.component.ts

fixed header now automatically shows login/logout

:bug: Header fixed

---

.vscode/settings.json
libs/client-lib/src/lib/collections/collections/collections.component.html
libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.html
libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.scss
libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.ts

View Collection page design has been updated, no new functionality added yet.

💄(UI): View Collection Page re-styled

---

libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.html

Game Sessions page design changed to adobe XD redesign, no functionality implemented yet

💄(UI): Game Sessions Page re-styled

---

libs/client-lib/src/lib/session/session/session.component.html
libs/client-lib/src/lib/session/session/session.component.scss

Sessions page has been re-styled to match adobe XD design, portions like image and sessions specific data empty until script execution is complete.

💄(UI): Sessions Page re-styled

---

libs/client-lib/src/lib/collections/collections/collections.component.html
libs/client-lib/src/lib/shared/components/header/header.component.html
libs/client-lib/src/lib/shared/components/header/header.component.scss
libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.html
libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.scss

View collections page visual fix.

💄(UI): View Collections fix

---

libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
libs/client-lib/src/lib/board-game-search/pagination/pagination.component.html
libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
libs/client-lib/src/lib/shared/components/header/header.component.html
libs/client-lib/src/lib/shared/components/header/header.component.scss

Board games page has been partially redesigned to the new adobe XD design.

💄(UI): Board Games page partial re-design

---

libs/api-lib/src/lib/services/compiler/compiler.service.ts
libs/client-lib/src/lib/shared/components/footer/footer.component.ts

Fixed identifier token being chosen over other tokens

:bug: Fixed identifier token

---

libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.html
libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
libs/client-lib/src/lib/shared/components/header/header.component.ts

Tyepscript methods Input and Output added to correspond with javascript DSL.

💩(UI): Addition of Input and Output methods for Script Executer

---

libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.ts
libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.ts

Board Games page has been completed and now has 2 side tabs for top games and recently viewed along with the functionality for displaying their respective contents.

💄(UI): Completion of Board Games Page

---

libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.html
libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.scss
libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.ts

Add to collections page has been redesigned.

💄(UI): Redesign of add to collections page

---

libs/api-lib/src/lib/services/compiler/compiler.service.ts
libs/client-lib/src/lib/editor/editor/editor.component.ts
templates/ActionTemplate.js
templates/script.js
templates/test.js

Added semantics for the action structure of the dsl

Visitor functionality added

---

libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
libs/client-lib/src/lib/home/carousel1/carousel1.component.ts
libs/client-lib/src/lib/home/home/home.component.scss
libs/client-lib/src/lib/script-detail/comment-form/comment-form.component.html
libs/client-lib/src/lib/script-detail/comment-form/comment-form.component.scss
libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.html
libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.scss
libs/client-lib/src/lib/shared/components/header/header.component.html
libs/client-lib/src/lib/shared/components/header/header.component.ts
libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.html
libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.scss
yarn.lock

Visual bug fixes on multiple pages.

🐛(UI): Visual bug fixes

---

libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts

Basic session data acquisition.

💩(UI): Session data acquisition from script execution

---

libs/api-lib/src/lib/models/general/tokens.ts
libs/api-lib/src/lib/services/compiler/compiler.service.ts
templates/ActionTemplate.js
templates/test.js
uploads/development/scripts/62f132f727b0db9634783a03/build/main.js
uploads/development/scripts/62f132f727b0db9634783a03/src/main.txt

Fixed issue with await, now inputs will wait to get user value instead of reading a promise object. removed console access from dsl users. Updated rule for output. changed templates accordingly.

:bug: Fixed await :fire: removed insecure methods

---

libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
libs/client-lib/src/lib/editor/editor/editor.component.ts

Drag and drop functionality from side bar to content page.

💄(VDSL): Drag and Drop functionality

---

libs/api-lib/src/lib/models/general/tokens.ts
libs/api-lib/src/lib/services/compiler/compiler.service.ts

Added removing Array elements by index to the dsl.

:sparkles: Added removing array elements by index

---

apps/client/ngsw-config.json
apps/client/src/app/app.component.ts
apps/client/src/app/app.module.ts
libs/api-lib/src/lib/services/alert/alert.service.ts
libs/client-lib/src/lib/collections/collections/collections.component.html
libs/client-lib/src/lib/collections/collections/collections.component.ts
libs/client-lib/src/lib/collections/create-collection/create-collection.component.ts
libs/client-lib/src/lib/google-login/GoogleAuth/google-auth.service.ts
libs/client-lib/src/lib/home/home.module.ts
libs/client-lib/src/lib/home/home/home.component.html
libs/client-lib/src/lib/home/home/home.component.scss
libs/client-lib/src/lib/home/home/home.component.ts
libs/client-lib/src/lib/shared/components/header/header.component.ts
libs/client-lib/src/lib/shared/services/alert/alert.service.ts

Reverts COS301-SE-2022/Board-Game-Companion-App#310

Revert "Revert "Home""
